--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/DeviceACM
build-by-default: false
branches:
- PM4
projects:
  DeviceACM:
    path: ""
    icon: icon-deviceacm.png
    lint:
      phpstan: false
...
