--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/DeviceACM
build-by-default: true
branches:
- PM4
projects:
  DeviceACM:
    path: ""
    icon: icon.png
    lint:
      phpstan: false
...
